data:
  path_to_data: ../DaNetQA
  train_filename: train.jsonl
  validation_filename: val.jsonl
  test_filename: val.jsonl
  text_field_name: passage
  quest_field_name: question
  label_field_name: label
  path_to_test_pred_scores: output/pred.txt

model:
#  model_name: sberbank-ai/ruBert-base    # pretrained model from Transformers 
  model_name: DeepPavlov/rubert-base-cased-sentence    # pretrained model from Transformers 
  max_seq_length: 256                    # depends on your available GPU memory (in combination with batch size)
  num_classes: 5

training:
  learn_rate: 3e-5                       # learning rate is typically ~1e-5 for transformers
  num_epochs: 40                          # smth around 2-6 epochs is typically fine when finetuning transformers
  accum_steps: 4                         # one optimization step for that many backward passes
  batch_size: 8                         # depends on your available GPU memory (in combination with max seq length)
  log_dir: logdir                        # for training logs and tensorboard visualizations
  fp16_params: None                      # fp16 support

general:
  seed: 17                               # random seed for reproducibility
